# Generated by Django 5.2 on 2025-06-27 19:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('image', models.ImageField(blank=True, null=True, upload_to='patients/', verbose_name='Patient Image')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Note Text')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Note Date')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_text', models.TextField(verbose_name='Diagnosis Text')),
                ('xray_image', models.ImageField(blank=True, null=True, upload_to='diagnosis/xrays/', verbose_name='X-ray Image')),
                ('model_image', models.ImageField(blank=True, null=True, upload_to='diagnosis/models/', verbose_name='Model Image')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Diagnosis Date')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.patient')),
            ],
        ),
    ]
